### PR TITLE
Bug inlinetree

### LINKED ISSUE #222: Bug in inlinetree evaluation
https://github.com/jolie/jolie/tree/bug_inlinetree

### PR DESCRIPTION
**Pull request by klag**
Fixed #222

### CODE REVIEW

File: jolie/src/main/java/jolie/runtime/expression/InlineTreeExpression.java [hunk 1]
```diff
@@ -57,7 +58,17 @@ public Operation cloneOperation( TransformationReason reason )
 		@Override
 		public void run( Value inlineValue )
 		{
-			path.getValue( inlineValue ).deepCopyWithLinks( expression.evaluate() );
+			if ( expression instanceof VariablePath ) {
+				Object myObj = (((VariablePath) expression).getValueOrValueVector());
```
Comment (fmontesi) [inline jolie/src/main/java/jolie/runtime/expression/InlineTreeExpression.java:62]: you can remove the outermost parentheses ().

File: jolie/src/main/java/jolie/runtime/expression/InlineTreeExpression.java [hunk 2]
```diff
@@ -57,7 +58,17 @@ public Operation cloneOperation( TransformationReason reason )
...
+				if ( myObj instanceof Value ) {
```
Comment (fmontesi) [inline jolie/src/main/java/jolie/runtime/expression/InlineTreeExpression.java:63]: please make this an if ( myObj instanceof Value ) { ... } else if ( myObj instanceof ValueVector ) { ... } else { throw new RuntimeException( "incomplete case analysis" ); }

File: test/primitives/inline_trees.ol [hunk 3]
```diff
@@ -57,4 +58,18 @@ define doTest
 	if ( s_b != s_inline ) {
 		throw( TestFailed, "Inline tree does not match composition of sub-trees" )
 	}
+
+	for( i = 0, i < 10, i++ ) {
+		z.u[ i ] = i
+	}
+	w << { .u << z.u }
```
Comment (fmontesi) [inline test/primitives/inline_trees.ol:65]: You can use the modern syntax without dot:
```jolie
w << { .u << z.u }
```
